services:
  postgres:
    image: postgres:16
    container_name: myreviews_app_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: myreviews_app_local
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  postgres_test:
    image: postgres:16
    container_name: myreviews_app_postgres_test
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: myreviews_app_local_test
    ports:
      - '5434:5432'
    volumes:
      - postgres_test_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  postgres_data:
  postgres_test_data:
